name: finearts
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  firebase_storage: ^11.7.6
  url_launcher: ^6.2.6
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
